version: '3'

services:
  db:
    container_name: db
    build: ./db
    user: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${USERDB}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${PASSWORDDB}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRRES_INIT_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c wal_log_hints=on
      -c archive_mode=on
      -c archive_command="cp %p /db/archive/%f"
      -c log_replication_commands=on
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  db_repl:
    container_name: db_repl
    build: ./db_repl
    user: postgres
    restart: always
    ports:
      - 5423:5432
    environment:
      POSTGRES_USER: ${REPLUSER}
      POSTGRES_PASSWORD: ${REPLPASSWORD}
    depends_on:
      - db
  bot:
    container_name: bot
    build: ./bot
    ports:
      - "3030:3030"
    environment:
      - TOKEN=${TOKEN}
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${HOSTUSER}
      - PASSWORD=${PASSWORD}
      - USERDB=${USERDB}
      - PASSWORDDB=${PASSWORDDB}
      - HOSTDB=${HOSTDB}
      - PORTDB=${PORTDB}
      - DATABASE=${DATABASE}

    depends_on:
      - db
      - db_repl
