CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'kali';

CREATE TABLE emails (
Email_id SERIAL PRIMARY KEY,
Email VARCHAR(255)
);

CREATE TABLE numbers (
Number_id SERIAL PRIMARY KEY,
Number VARCHAR(30)
);
